### ISSUE TITLE
ImportError: dynamic module does not define module export function when installing the Python package via setuptools

### ISSUE THREAD

**Issue by fbartolic** [valboz/VBBinaryLensing#1]
Currently the Python module installation via setuptools is not working. One can compile a module with
`Makefile.Python` in the `src`  folder and then import it into Python within that folder but the compilation 
via `python setup.py install` is broken in some way because the package import fails. 

I've asked a question about this on StackOverflow at https://stackoverflow.com/questions/49111874/creating-a-python-package-for-c-code-wrapped-with-pybind11-using-setuptools but it doesn't look like I'll get an answer. It might be worthwhile to raise an issue on the pybind11 setuptools example repo: https://github.com/pybind/python_example.

**Comment by ebachelet** [comment]
Found this on pybind11 doc : 
https://pybind11.readthedocs.io/en/stable/faq.html

“ImportError: dynamic module does not define init function”

You are likely using an incompatible version of Python (for instance, the extension library was compiled against Python 2, while the interpreter is running on top of some version of Python 3, or vice versa).

**Comment by fbartolic** [comment]
Solved in 6e79d752093cd5e265189a475c00e812574d4ac0. The issue was that the module name in `bindings.cpp` didn't match the one in `setup.py`.
