### ISSUE TITLE
Continue creating release on GitHub

### ISSUE THREAD

**Issue by ketozhang** [valboz/VBBinaryLensing#15]
Please continue tagging new releases as you're uploading the wrapper to PyPI.

For my use case, I depend on also the C++ source code and not only the wrapper, so I need a way to lock my dependencies on a git tag version. Currently I am maintaining a repository that mirrors the releases of  http://www.fisica.unisa.it/gravitationastrophysics/VBBinaryLensing.htm. I'd like to stop doing this.

**Comment by ketozhang** [comment]
@ebachelet

**Comment by ebachelet** [comment]
Thanks for the comment, we will tag the new releases in the future.

**Comment by valboz** [comment]
Solved
