### ISSUE TITLE
Local install fails with missing Python.h file 

### ISSUE THREAD

**Issue by rachel3834** [valboz/VBBinaryLensing#20]
I tried to install VBB by cloning the Github repo and running the python setup.py installation locally as a test, but ran into the following error:

x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include -I/data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include -I/data/software/pylima_venv3_11/include -I/usr/include/python3.11 -c VBBinaryLensing/lib/python_bindings.cpp -o build/temp.linux-x86_64-3.11/VBBinaryLensing/lib/python_bindings.o -DVERSION_INFO="3.6.1" -std=c++17 -fvisibility=hidden
In file included from /data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include/pybind11/detail/../attr.h:13,
                 from /data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include/pybind11/detail/class.h:12,
                 from /data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include/pybind11/pybind11.h:13,
                 from VBBinaryLensing/lib/python_bindings.cpp:1:
/data/software/VBBinaryLensing/.eggs/pybind11-2.11.1-py3.11.egg/pybind11/include/pybind11/detail/../detail/common.h:266:10: fatal error: Python.h: No such file or directory
  266 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

**Comment by ebachelet** [comment]
Can you try pip install . instead?

**Comment by rachel3834** [comment]
[Reading](https://betterstack.com/community/questions/how-to-fix-python-h-no-such-file-or-directory/) up on this issue, it appears that to fix it requires the python-dev package, which I then attemped to install.  
However, it appears that this is a Python2 plug in, which is [depreciated](https://unix.stackexchange.com/questions/708493/python-dev-package-installation-error).  

I tried to install the python2-dev package (supposed to be for backcompatibility) but this doesn't fix the problem, and installing VBB under Ubuntu 20.X fails with the same error as above. 

I've tried both python setup.py install and pip install .

**Comment by ketozhang** [comment]
@rachel3834 Can you run `python-config --includes`. It should output at least 1 directory path. Please then check if those directory includes the `Python.h` file.

Please make sure you're using the python environment that produced this error (e.g., activate the virtual environment if you're using one). You can also provide us the output of these commands:

```
which python
which pip
which python-config
```

**Comment by rachel3834** [comment]
Thanks for your responses.  I was definitely within the python venv at the time, and after discussing this with Etienne, I opted to build a fresh venv, using the requirements from his machine.  This appears to have been successful, so I guess my old venv was corrupted.
