### ISSUE TITLE
Invalid character in setup.py

### ISSUE THREAD

**Issue by ebachelet** [valboz/VBBinaryLensing#3]
Hi there

I suceed to install VBBinaryLensing, awesome! Just one caveat. When downloaded and try to install, I faced an issue with your name Fran : 

File "setup.py", line 95
SyntaxError: Non-ASCII character '\xc4' in file setup.py on line 95, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

The issue come from the "c" of Bartolic. When I replace the accent on "c" with a standard "c", problem solved.
I had the same issue on my desktop in SB, which runs the same Ubuntu version as my laptop, Ubuntu16.
Note sure if this is a multi-os/system issue, it might highly be, so I recomant we switch your name to a standard "c" (sorry :) ). Except if you explain this good and find an easy fix.

**Comment by fbartolic** [comment]
Fixed in c7c96fd209adc7100cec6bfe7e4c93468b4888aa. Typed that accidentaly.
