### ISSUE TITLE
default accuracy of magnification without limb-darkening effect

### ISSUE THREAD

**Issue by rpoleski** [valboz/VBBinaryLensing#32]
The default value of `Tol` is 0.01. Does this mean that when I call a function with accuracy parameter, e.g., `BinaryMag2()` then the magnification is accurate to 0.01?

**Comment by valboz** [comment]
Yes, that's what I "promise". In some exceptional cases you might find slightly higher error.
This means that 
|true_magnification - BinaryMag2_magnification| < Tol
You can change Tol as you like, until you meet numerical accuracy limitations.

**Comment by rpoleski** [comment]
Ok, I just thought the default was 0.001, not 0.01.

**Comment by valboz** [comment]
OK, no problem!
