### ISSUE TITLE
Unexpected Behavior in Single Lens Model Simulation with ρ Parameter

### ISSUE THREAD

**Issue by Atousa-Kalantari** [valboz/VBBinaryLensing#35]
Hi,

I am using the VBBinaryLensing package to simulate a single lens model, and I encountered an issue with the magnification vs. time plot when setting the following parameters:

Blending ratio: 0.4 (40% of the source)
t₀: 7.500106
tₑ: 0.170188
u₀: 0.73015
ρ: 242.153090

```
import VBBinaryLensing
vbb = VBBinaryLensing.VBBinaryLensing()
vbb.LoadESPLTable("./ESPL.tbl")
vbb.Tol = 1.e-4
vbb.a1 = 0.0

m = []
for t in t1:
    u = np.sqrt(u0 * u0 + ((t - t0) * (t - t0)) / (tE * tE))
    As = vbb.ESPLMag2(u, ros)
    Astar = As * blend + 1.0 - blend
    m.append(Astar)
```

The magnification vs. time plot appears unusual:
<img width="449" alt="Screenshot 2024-10-11 at 11 15 01 PM" src="https://github.com/user-attachments/assets/d4143c00-9039-4546-850d-7a23a37ab670">

However, when I set ρ = 0, the model behaves as expected, and the plot looks like this:
<img width="436" alt="Screenshot 2024-10-11 at 11 01 13 PM" src="https://github.com/user-attachments/assets/cc2602be-2e78-4142-bc6e-9d52c09925b8">

I would greatly appreciate your help in understanding why this behavior occurs and how I might resolve the issue.

**Comment by ebachelet** [comment]
If I read correctly, rho=242. I believe VBB is working only until rho=10

**Comment by valboz** [comment]
VBBinaryLensing works until rho=100, as discussed in [SingleLenses](https://github.com/valboz/VBBinaryLensing/blob/master/docs/SingleLenses.md). So, your rho=242 is out of range for VBBinaryLensing. Sorry

**Comment by Atousa-Kalantari** [comment]
Oh, I didn’t know that! Thanks a lot for the clarification!
