### ISSUE TITLE
bindings.cpp not found -> please update setup

### ISSUE THREAD

**Issue by mpgh** [valboz/VBBinaryLensing#4]
When I call setup.py I am getting the following error: VBBinaryLensing/lib/bindings.cpp: No such file or directory
That seems to have changed recently and setup.py needs to be updated accordingly.
Many thanks!

**Comment by fbartolic** [comment]
Fixed in bb675080a629ce8799657aacdc841d34b9e2311c. We're still working on writing some tests and setting up Travis to catch these issues. Should be a lot more polished in about a week.
