### ISSUE TITLE
Compilation performance

### ISSUE THREAD

**Issue by ebachelet** [valboz/VBBinaryLensing#5]
Including VBB2.0 inside pyLIMA, I start to work in terms of performance of the current python wrapping.

It looks, as in the past with SWIG, that the performance are impacted regarding the flags used during the cpp compilation. I run a little test consisting of 10000 calls of BinaryMag2 and BinaryMag0, and obtain for 3 tests on the current implementation : 

10.853657245635986 s
11.192471742630005 s
11.608935117721558 s

As suggested by Markus in the past, I added two flags in the compilation : 

opts.append('--fast-math')
opts.append('-lm')

and obtains : 

10.323110103607178 s
10.13972783088684 s
10.425249576568604 s

This is roughly 1s faster. We need to understand this. @valboz, what are your options for your c++ compilations? Also, if you could run a test using the same parameters, that could be great : 

VBB.Tol = 0.001
VBB.RelTol = 0.001

s = 1.
q = 0.0002
y1 = 0.0005 
y2 = 0.0005 
rho = 0.0033

@valboz, I think it could be valuable to have Markus input on this (@mpgh). Could you add it in the project?

**Comment by valboz** [comment]
Markus has already been invited to collaborate but he has not responded yet.

I have not played too much with C++ options. I have just accepted Visual Studio defaults. Indeed there are some possible optimizations in the compilation that might speed-up. I used to try some of them somehow. If you find an optimal configuration, it may be worth advertising it in the Makefile.

**Comment by fbartolic** [comment]
I don't know much about compiler optimizations. Judging by <a href="https://stackoverflow.com/questions/7420665/what-does-gccs-ffast-math-actually-do">this
</a> answer, the `--fast-math` breaks IEEE 754 standard, are we okay with that? I'm thinking it could be a problem for reproducibility  on different hardware architectures.

**Comment by mpgh** [comment]
I thought I actually have responded to the invitation, but that wasn't processed properly. I gladly accept the invitation (and as you have noticed started testing).

As far as the issue with --fast-math is concerned, I would suggest to keep it and document the system the code is running on. That should be good practice anyway.

https://docs.python.org/2/library/platform.html

**Comment by fbartolic** [comment]
Closing for now.
