### ISSUE TITLE
Tol and RelTol

### ISSUE THREAD

**Issue by ebachelet** [valboz/VBBinaryLensing#6]
It looks at the time been that both Tol and RelTol conditions should be matched to stop loop. Example line 831 : 

while (((flag<nannold + 5) && (currerr>Tolv) && (currerr>RelTol*Mag)) || (nannuli<minannuli)) 

Is it not desirable to have an OR condition there?

**Comment by valboz** [comment]
Hi Etienne, you are taking the wrong way: the loop continues as long as the error is larger than Tol AND the relative error is larger than RelTol. As soon as one of the goals is reached, the loop exits.
